### ISSUE TITLE
Dashboard last seen value is same for all devices in a location

### ISSUE THREAD

**Issue by brandonjank** [uidaho/smartsettia#108]
See screenshot:
![image](https://user-images.githubusercontent.com/784730/32624603-8d4596d6-c53e-11e7-991d-2baf371ee39f.png)

**Comment by brec9824** [comment]
Yeah that is because when the migration that added the new field for storing the last API update to the device table it uses the current time as default. So all devices that aren't updating anymore will have the same value. The only way around this is to set the default to the normal updated_at time but the updated_at time is changed from any device change so it will be inaccurate. So pretty much either way the last seen value will be incorrect for devices that were created before the migration and don't receive updates.

**Comment by brandonjank** [comment]
Gotcha, can probably leave it as is then. Closing.

**Comment by brandonjank** [comment]
Looks like the default value was set in the database rather than by the application.

**Comment by brec9824** [comment]
Closing fixed with pull request #111
