### ISSUE TITLE
Lack of user input sanitizing allows for JavaScript injections

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#93]
## Expected Behavior

Input validation combined with input sanitizing should adequately sanitize all user input to prevent all kinds of attacks like SQL injection, JavaScript injection, etc.

## Current Behavior

Currently there is no input sanitizing other then using Laravel validators. Combined with the use of the nonrestrictive string rule allows users to input JavaScript that will be run for the client when the string gets displayed.

## Possible Solution

1. Replace the string rule with the regex rule and only allow specific subset of input that will be safe.
2. Leave the string rule and sanitize all strings using php's [sanitize filters](http://php.net/manual/en/filter.filters.sanitize.php).
3. Do both for layered security.

## Steps to Reproduce (for bugs)

1. Choose an input that is currently using the string rule for validation
2. Input <script>alert("Hello")</script>
3. Submit the valid input
4. Go to the page that displays the given text and you should receive an alert saying "Hello"

## Context

Making this change will prevent certain attacks against the server and the users.

**Comment by brandonjank** [comment]
We use Eloquent models, so SQL injection is not possible. It does not execute direct SQL statements, it builds them. However, script injection is very possible!
We should be using {{{ $var }}} in our blades to strip html on output for variables we don't need html (which is most if not all).

An alternative solution is using form requests and filter_var to sanitize string input:
http://www.easylaravelbook.com/blog/2015/03/31/sanitizing-input-using-laravel-5-form-requests/

It is generally recommended that we sanitize output (using {{{}}}) rather than input.

**Comment by brec9824** [comment]
You are right about Laravel 5 protecting against SQL injection I was looking at some stuff for Laravel 4 and they had some issues that still allowed for SQL injection on specific types of statements. Using {{{ $var }}} everywhere is good but if it is forgotten anywhere then we are vulnerable. For example how we are displaying the datatables is vulnerable. Only sanitizing output is necessary when you don't know exactly if you may need to receive special characters for valid input. But we know exactly what we need as valid input so we should be sanitizing all input. That way we don't have to be worrying about forgetting {{{}}}, sanitizing the datatables, and sanitizing html generated by javascript.

**Comment by brandonjank** [comment]
DataTables are secure against injection as long as the field is not in the raw list.

**Comment by brandonjank** [comment]
Turns out, using {{{ $var }}} is unnecessary in Laravel 5.2 and up. By default all {{ $var }} are escaped now. Using {!! $var !!} overrides this behavior and will not escape the string.

This leaves us with the recommended option:
Use the a regex validation for all string and use the proper validation for all fields.
e.g. phone number should use 'phone' validation.

I'd say that names should have only spaces hyphens underscores, letters, and numbers:
```regex:[A-Za-z0-9\-\_\.\s] ```

**Comment by brandonjank** [comment]
@brec9824 I believe you have updated validations for all the inputs with #113. Because we are strictly validating all input and, since we use 5.5, output is escaped automatically. Shall we double check all validations and ```{!! $var !!}``` and close this?

**Comment by brec9824** [comment]
@brandonjank From my testing all the new validation rules should prevent any Javascript or html code from being saved into our database. So I believe we are covered now and should be good. I going to close this issue but if you think of anything else just reopen and we can get it added.
